export enum Tokens {
  NUMBER = 'NUMBER',
  IDENTIFIER = 'IDENTIFIER',
  ADDITION = '+',
  SUBTRACTION = '-',
  MULTIPLICATION = '*',
  DIVISION = '/',
  EXPONENTIATION = '^',
  PARENTHESIS_LEFT = '(',
  PARENTHESIS_RIGHT = ')',
}
